stadline_tasks_page_log:
    path:     /log/phase
    defaults: { _controller: StadlineTasksBundle:Default:PageLog}

stadline_tasks_page_log_error:
    path:    /log/error
    defaults: { _controller: StadlineTasksBundle:Default:PageLogError}

stadline_tasks_page_assignfacture:
    path:    /log/assign
    defaults: { _controller: StadlineTasksBundle:Default:assignfacture}

