imports:
    - { resource: config_dev.yml }

parameters:
    stadline_sugar_crm.client.class: Stadline\SugarCRMBundle\Mock\SugarMock
    stadline_front.soap_service: Stadline\LundiMatinClientBundle\Mock\SoapServiceMock

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
