stadline_public_connector:
    resource: "@StadlinePublicConnectorBundle/Resources/config/routing.yml"
    prefix:   /

stadline_tasks:
    resource: "@StadlineTasksBundle/Resources/config/routing.yml"
    prefix:   /

stadline_front:
    resource: "@StadlineFrontBundle/Resources/config/routing.yml"
    prefix:   /

stadline_zendesk:
    resource: "@StadlineZendeskBundle/Resources/config/routing.yml"
    prefix:   /

