<?php

namespace Stadline\TasksBundle;

use Stadline\TasksBundle\DependencyInjection\CompilerPass\AssignCompilerPass;
use Stadline\TasksBundle\DependencyInjection\CompilerPass\StructurePhaseCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class StadlineTasksBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $container->addCompilerPass(new AssignCompilerPass());
        $container->addCompilerPass(new StructurePhaseCompilerPass());
    }


}
