parameters:
    stadline_zendesk.client.class: Zendesk\API\HttpClient
    stadline_zendesk.auth:
       username: %stadline_zendesk.config.username%
       token : %stadline_zendesk.config.token%

services:
    stadline_zendesk_client:
        class: %stadline_zendesk.client.class%
        arguments:
            - %stadline_zendesk.config.domain%
            - %stadline_zendesk.config.username%
        calls:
            - [ setAuth,    ['basic', %stadline_zendesk.auth%]]