stadline_front_facture_pdf:
    path:     /facture/pdf/{refDocEncrypt}
    defaults: { _controller: StadlineFrontBundle:Default:pdf }
    
stadline_front_factures:
    path:     /factures/{hashedRef}
    defaults: { _controller: StadlineFrontBundle:Default:factures }

stadline_front_hash:
    path:     /hash/{refContact}
    defaults: { _controller: StadlineFrontBundle:Default:hash, refContact:1 }

stadline_front_state:
    path:    /factures/{hashedRef}/{state}
    defaults: { _controller: StadlineFrontBundle:Default:state }

stadline_front_test_sugar:
    path:     /testsugar
    defaults: { _controller: StadlineFrontBundle:Default:testSugar }
