services:
    stadline_front.soap_service:
        class: Stadline\FrontBundle\Service\SoapService
        arguments:
            - %api_url%
            - %api_ref_factures%
            - %api_username%
            - %api_password%


    stadline_sugar_crm_client:
             class: %stadline_sugar_crm.client.class%
             arguments:
                 - %stadline_sugar_crm.config.base_url%
                 - %stadline_sugar_crm.config.username%
                 - %stadline_sugar_crm.config.password%

